name: Front - Back

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Pull le repo du frontend
        uses: actions/checkout@v4

      - name: Pull le repo du backend
        uses: actions/checkout@v4
        with:
          repository: Cemus/fil-rouge-back
          path: backend

      - name: Installation de Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Installation des dépendances frontend
        run: npm install

      - name: Installation des dépendances backend
        run: |
          cd backend
          npm install

      - name: Lancement du backend
        run: |
          cd backend
          npm start &
        env:
          PORT: 3000
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:3000/health

      - name: Lancement du frontend
        run: npm run dev &
        env:
          NODE_ENV: test

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:5173

      - name: Runner les tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: http://localhost:5173
          browser: chrome

      - name: Upload Cypress videos and screenshots (en cas d'échec)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
