name: Front - Back

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  front-back-cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Frontend
        uses: actions/checkout@v4
        with:
          path: frontend

      - name: Pull Backend
        uses: actions/checkout@v4
        with:
          repository: Cemus/fil-rouge-back
          path: backend

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Installation des dépendances front
        working-directory: frontend
        run: npm install

      - name: Installation des dépendances back
        working-directory: backend
        run: npm install

      - name: Lancement du backend
        working-directory: backend
        run: |
          npx nodemon server.ts &
        env:
          PORT: 3000
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Attendre le back...
        run: npx wait-on http://localhost:3000/api/health --timeout 30000

      - name: Lancer le frontend
        working-directory: frontend
        env:
          VITE_API_URL: http://localhost:3000
        run: |
          npm run dev &

      - name: Attendre le front...
        run: npx wait-on http://localhost:5173 --timeout 30000

      - name: Runner les tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: http://localhost:5173
          browser: chrome
          working-directory: frontend

      - name: Upload des screens
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            frontend/cypress/videos
            frontend/cypress/screenshots
